Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Documentation:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 24
