ENV['ACCESS_KEY'] = 'ACCESS_KEY'
ENV['SECRET_KEY'] = 'SECRET_KEY'
ENV['EWALLET_URL'] = 'https://example.com/api'

ENV['PROVIDER_USER_ID'] = 'provider_user_id01'
ENV['ACCOUNT_ID'] = 'acc_01ce6bqk1748sp9766qz7y0ghz'
ENV['TOKEN_ID'] = 'tok_OMG_01CE6BQN433JCYN8C1GFT9YXRS'

# Base64 Encoded:
# OMGServer QUNDRVNTX0tFWTpTRUNSRVRfS0VZ
